# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Dylan Krajnc
title: BSc Computer Science Student
email: u17029318@tuks.co.za
phone: 078 907 5622
cv   : "resume.pdf"
#website: Your website (eg. https://google.com)(optional)

# Social links
#twitter_username: jekyllrb
github_username:  Dylan-Krajnc
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#linkedin_username: jekyll
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

# About Section
about_title: Dylan Krajnc
about_profile_image: images/myDP.jpeg
about_content: | # this will include new lines to allow paragraphs
  A final year student at the University of Pretoria studying to obtain a Bachelor's of Science in Computer Science. 
  
  
  Eager to learn new skills and technologies that will allow me to solve new problems and create better software. Even more willing to do so when working with a team to accomplish a task. 

#  You can even add paragraphs by using empty lines like this and add anything else markdown supports such as
#    - [My Awesome Resume](https://moya10.github.io/awesome-cv/resume.pdf)
#    - Tables
#    - Links
#   - Images

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
more_title: Competitions
more_content: | # this will include new lines to allow paragraphs
  - 2019 Catalyst Coding Competiton

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "makefile",
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
